# Generated by Django 5.1.3 on 2024-12-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discoteca',
            old_name='usuario',
            new_name='user',
        ),
    ]
