# Generated by Django 5.1.3 on 2024-12-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_usuario_discoteca_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoteca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='discotecas/'),
        ),
    ]
