# Generated by Django 5.1.4 on 2024-12-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_discoteca_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoteca',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
