# Generated by Django 5.1.4 on 2024-12-18 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discoteca',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_discotecas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discoteca',
            name='imagen',
            field=models.ImageField(default='', upload_to='discotecas/'),
            preserve_default=False,
        ),
    ]
